version: '3.9'

services:
  nginx:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./../public/assets:/application/public/assets
      - ./../storage/app/public:/application/public/storage
    ports:
      - ${NGINX_PROXY_HTTP_PORT}:80
    networks:
      - backend

  php-fpm:
    build:
      context: ../
      dockerfile: docker/dockerfiles/php-fpm/Dockerfile
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/dockerfiles/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      - backend
    links:
      - postgres
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ./redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend

  postgres:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/pgsql/Dockerfile
    working_dir: /application
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../:/application
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - backend

  cron:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/php_cron/Dockerfile
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ../:/application
    networks:
      - backend
    links:
      - postgres
      - redis

  queue-worker:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/php-fpm/Dockerfile
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/dockerfiles/php_cli/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/99-overrides.ini
    command: [ "php", "artisan", "queue:listen", "--delay=0", "--tries=3" ]
    networks:
      - backend
    links:
      - postgres
      - redis

  elasticsearch:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/elasticsearch/Dockerfile
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    restart: unless-stopped
    ports:
      - 9200:9200
    networks:
      - backend
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

networks:
  backend:
    name: ${COMPOSE_PROJECT_NAME}_network
    driver: bridge

volumes:
  pgdata:
    external: true
  pgadmin:
  #  mysql:
  redis:
  es_data:
