<?php

namespace App\Services\General;

use App\Repositories\General\CategoryRepository;

class CategoryService extends CategoryRepository
{


    public function index(string $type)
    {
        return parent::index($type); // TODO: Change the autogenerated stub
    }
}
